# art_pals { #artpack.art_pals }

```python
art_pals(pal='ocean', n=5, direction='regular', randomize=False)
```

The artpack palette picker. The `art_pals` function consists of 18 palettes.

## Parameters {.doc-section .doc-section-parameters}

| Name      | Type   | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | Default     |
|-----------|--------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------|
| pal       | str    | A character string of the desired artpack palette. Default is "ocean".  The 18 artpack palettes include:  &#x2022; "arctic" - Icy blue and white colors<br> &#x2022; "beach" - Sand-colored tans and ocean-colored blue colors<br> &#x2022; "bw" - A gradient of black to white colors<br> &#x2022; "brood" - A gradient of different shades of dark gray and black colors<br> &#x2022; "cosmos" - Nebula-inspired blue, purple, and pink colors<br> &#x2022; "explorer" - Pokemon-type inspired colors<br> &#x2022; "gemstones" - Birthstone/Mineral-inspired colors<br> &#x2022; "grays" - A gradient of dark, medium, and light gray colors<br> &#x2022; "icecream" - A light pastel palette of cream, blue, brown, and pink colors<br> &#x2022; "imagination" - 90's school supply-inspired colors<br> &#x2022; "majestic" - Shades of majestic purple colors<br> &#x2022; "nature" - A mix of tan, brown, green, and red colors<br> &#x2022; "neon" - A neon spectrum of rainbow colors<br> &#x2022; "ocean" - A gradient of dark to light blue colors<br> &#x2022; "plants" - A gradient of dark to light green colors<br> &#x2022; "rainbow" - A vibrant mix of rainbow colors<br> &#x2022; "sunnyside" - A retro-inspired mix of pink, orange, and yellow colors<br> &#x2022; "super" - A marveling mix of heroic colors | `'ocean'`   |
| n         | int    | The number of colors desired in the output. Default is 5. Must be a positive integer with a value greater than 0.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | `5`         |
| direction | str    | The direction of the palette. Default is "regular". Options: "regular", "reg", "reverse", "rev"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | `'regular'` |
| randomize | bool   | Determines if the colors in the palette appear in a randomized order. Default is False.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | `False`     |

## Returns {.doc-section .doc-section-returns}

| Name   | Type        | Description                        |
|--------|-------------|------------------------------------|
|        | list of str | A list of hexadecimal color codes. |

## Examples {.doc-section .doc-section-examples}

```python
>>> colors = art_pals("rainbow", n=5)
>>> len(colors)
5
```